# Generated by Django 4.2.6 on 2024-03-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('sponsor_type', models.CharField(choices=[('JISMONIY', 'Jismoniy shaxs'), ('YURIDIK', 'Yuridik shaxs')], default='JISMONIY', max_length=15)),
                ('balance', models.PositiveIntegerField()),
                ('sponsored', models.PositiveIntegerField(default=0)),
                ('phone_number', models.IntegerField()),
                ('company', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('MODERATION', 'Moderatsiya'), ('NEW', 'Yangi'), ('APPROVED', 'Tasdiqlangan'), ('CANCELED', 'Bekor qilingan')], default='NEW', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
